# This workflow builds the specified Docker images and pushes them and the
# README to the Docker Hub registry.
---
name: docker_build

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            tags: 'joshbeard/ansible:6.6.0,joshbeard/ansible:6,joshbeard/ansible:latest'
            build-args: ansible_version=6.6.0
          -
            tags: 'joshbeard/ansible:7.0.0rc1,joshbeard/ansible:7'
            build-args: ansible_version=7.0.0rc1

    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build latest
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}

  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/ansible
          readme: ./README.md
          description: Image containing Ansible installed from pip
