# This workflow builds the specified Docker images and pushes them and the
# README to the Docker Hub registry.
---
name: docker_build

on:
  push:
    branches:
      - 'master'

# Allow creating releases and packages.
permissions:
  packages: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - tags: 'joshbeard/ansible:10.1.0,joshbeard/ansible:10,joshbeard/ansible:latest,ghcr.io/joshbeard/ansible:10.1.0,ghcr.io/joshbeard/ansible:10,ghcr.io/joshbeard/ansible:latest'
            build-args: ansible_version=10.1.0

          - tags: 'joshbeard/ansible:9.7.0,joshbeard/ansible:9,joshbeard/ansible:latest,gchr.io/joshbeard/ansible:9.7.0,ghcr.io/joshbeard/ansible:9,ghcr.io/joshbeard/ansible:latest'
            build-args: ansible_version=9.7.0

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Build Image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}

  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - name: Publish README to Docker Hub
        uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/ansible
          readme: ./README.md
          description: Image containing Ansible installed from pypi
