---
name: docker_build

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 6 * * 1"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          -
            tags: 'joshbeard/ansible:6.1.0,joshbeard/ansible:6,joshbeard/ansible:latest'
            build-args: ansible_version=6.1.0
          -
            tags: 'joshbeard/ansible:6.0.0'
            build-args: ansible_version=6.0.0
          -
            tags: 'joshbeard/ansible:5.10.0,joshbeard/ansible:5'
            build-args: ansible_version=5.10.0
          -
            tags: 'joshbeard/ansible:5.9.0'
            build-args: ansible_version=5.9.0
          -
            tags: 'joshbeard/ansible:5.8.0'
            build-args: ansible_version=5.8.0
          -
            tags: 'joshbeard/ansible:5.7.0'
            build-args: ansible_version=5.7.0
          -
            tags: 'joshbeard/ansible:5.6.0'
            build-args: ansible_version=5.6.0
          -
            tags: 'joshbeard/ansible:5.5.0'
            build-args: ansible_version=5.5.0
          -
            tags: 'joshbeard/ansible:5.4.0'
            build-args: ansible_version=5.4.0
          -
            tags: 'joshbeard/ansible:5.3.0'
            build-args: ansible_version=5.3.0
          -
            tags: 'joshbeard/ansible:4.0.0'
            build-args: ansible_version=4.0.0

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build latest
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ matrix.tags }}
          build-args: ${{ matrix.build-args }}
  doc:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@master
      - uses: meeDamian/sync-readme@v1.0.6
        with:
          user: ${{ secrets.DOCKERHUB_USERNAME }}
          pass: ${{ secrets.DOCKERHUB_TOKEN }}
          slug: joshbeard/ansible
          readme: ./README.md
          description: Image containing Ansible installed from pip
