# This workflow runs daily and deletes tags that have a scheduled deletion date
# listed in a table in the README.md file.
# It uses the action from https://github.com/joshbeard/docker-hub-tag-delete
name: delete_expired_image_tags

on:
  schedule:
    - cron: "0 23 * * *"
  push:
    branches:
      - 'master'

jobs:
  delete_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Docker Hub Tag Deleter
        uses: joshbeard/docker-hub-tag-delete@master
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub_repository: joshbeard/ansible
          markdown_file: README.md

