name: delete_expired_image_tags

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 6 * * 1"

jobs:
  delete_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Hub Tag Deleter
        uses: joshbeard/docker-hub-tag-delete@v1
        with:
          dockerhub_username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub_password: ${{ secrets.DOCKERHUB_TOKEN }}
          dockerhub_repository: joshbeard/ansible
          markdown_file: README.md

